In [1]:
import pandas as pd

pricing_df = pd.read_csv('../final_project_nt/DatafinitiElectronicsProductsPricingData.csv')
pricing_df

,id,prices.amountMax,prices.amountMin,prices.availability,prices.condition,prices.currency,prices.dateSeen,prices.isSale,prices.merchant,prices.shipping,...,name,primaryCategories,sourceURLs,upc,weight,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,AVphzgbJLJeJML43fA0o,104.99,104.99,Yes,New,USD,"2017-03-30T06:00:00Z,2017-03-10T22:00:00Z,2017...",False,Bestbuy.com,NaN,...,Sanus VLF410B1 10-Inch Super Slim Full-Motion ...,Electronics,https://www.amazon.com/Sanus-VLF410B1-10-Inch-...,7.93796E+11,32.8 pounds,NaN,NaN,NaN,NaN,NaN
1,AVpgMuGwLJeJML43KY_c,69.00,64.99,In Stock,New,USD,2017-12-14T06:00:00Z,True,Walmart.com,Expedited,...,Boytone - 2500W 2.1-Ch. Home Theater System - ...,Electronics,http://reviews.bestbuy.com/3545/4784804/review...,6.42015E+11,14 pounds,NaN,NaN,NaN,NaN,NaN
2,AVpgMuGwLJeJML43KY_c,69.00,69.00,In Stock,New,USD,2017-09-08T05:00:00Z,False,Walmart.com,Expedited,...,Boytone - 2500W 2.1-Ch. Home Theater System - ...,Electronics,http://reviews.bestbuy.com/3545/4784804/review...,6.42015E+11,14 pounds,NaN,NaN,NaN,NaN,NaN
3,AVpgMuGwLJeJML43KY_c,69.99,69.99,Yes,New,USD,2017-10-10T05:00:00Z,False,Bestbuy.com,NaN,...,Boytone - 2500W 2.1-Ch. Home Theater System - ...,Electronics,http://reviews.bestbuy.com/3545/4784804/review...,6.42015E+11,14 pounds,NaN,NaN,NaN,NaN,NaN
4,AVpgMuGwLJeJML43KY_c,66.99,66.99,Yes,New,USD,2017-08-28T07:00:00Z,False,Bestbuy.com,NaN,...,Boytone - 2500W 2.1-Ch. Home Theater System - ...,Electronics,http://reviews.bestbuy.com/3545/4784804/review...,6.42015E+11,14 pounds,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14587,AVpgibRDLJeJML43PTZX,65.99,65.99,NaN,NaN,USD,2015-09-05T00:00:00Z,True,NaN,USD 13.81 shipping,...,naxa - 2.1-Channel Soundbar with 50-Watt Digit...,Electronics,https://www.walmart.com/reviews/product/441840...,8.40005E+11,4.1 pounds,NaN,NaN,NaN,NaN,NaN
14588,AVpgibRDLJeJML43PTZX,58.99,58.99,Yes,New,USD,"2017-10-10T19:00:00Z,2017-09-06T17:00:00Z,2017...",False,Bestbuy.com,NaN,...,naxa - 2.1-Channel Soundbar with 50-Watt Digit...,Electronics,https://www.walmart.com/reviews/product/441840...,8.40005E+11,4.1 pounds,NaN,NaN,NaN,NaN,NaN
14589,AVpgibRDLJeJML43PTZX,58.49,58.49,In Stock,New,USD,2018-03-05T11:00:00Z,False,Walmart.com,Standard,...,naxa - 2.1-Channel Soundbar with 50-Watt Digit...,Electronics,https://www.walmart.com/reviews/product/441840...,8.40005E+11,4.1 pounds,NaN,NaN,NaN,NaN,NaN
14590,AVpgibRDLJeJML43PTZX,77.98,77.98,NaN,NaN,USD,2016-03-22T00:00:00Z,True,NaN,NaN,...,naxa - 2.1-Channel Soundbar with 50-Watt Digit...,Electronics,https://www.walmart.com/reviews/product/441840...,8.40005E+11,4.1 pounds,NaN,NaN,NaN,NaN,NaN
14591,AVpgibRDLJeJML43PTZX,71.95,71.95,NaN,new,USD,2015-12-05T00:00:00Z,False,Beach Audio Inc - Walmart.com,NaN,...,naxa - 2.1-Channel Soundbar with 50-Watt Digit...,Electronics,https://www.walmart.com/reviews/product/441840...,8.40005E+11,4.1 pounds,NaN,NaN,NaN,NaN,NaN

In [2]:
pricing_df.columns

Index(['id', 'prices.amountMax', 'prices.amountMin', 'prices.availability',
       'prices.condition', 'prices.currency', 'prices.dateSeen',
       'prices.isSale', 'prices.merchant', 'prices.shipping',
       'prices.sourceURLs', 'asins', 'brand', 'categories', 'dateAdded',
       'dateUpdated', 'ean', 'imageURLs', 'keys', 'manufacturer',
       'manufacturerNumber', 'name', 'primaryCategories', 'sourceURLs', 'upc',
       'weight', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29',
       'Unnamed: 30'],
      dtype='object')

In [3]:
pricing_df = pricing_df.rename(columns={'prices.amountMax':'prices_amountMax',
                                       'prices.amountMin':'prices_amountMin',
                                       'prices.availability':'prices_availability',
                                       'prices.condition': 'prices_condition',
                                       'prices.currency':'prices_currency',
                                       'prices.dateSeen': 'prices_dateSeen',
                                       'prices.isSale': 'prices_isSale',
                                       'prices.merchant': 'prices_merchant',
                                       'prices.shipping': 'prices_shipping',
                                       'prices.sourceURLs': 'prices_sourceURLs'})

In [4]:
pricing_df.columns

Index(['id', 'prices_amountMax', 'prices_amountMin', 'prices_availability',
       'prices_condition', 'prices_currency', 'prices_dateSeen',
       'prices_isSale', 'prices_merchant', 'prices_shipping',
       'prices_sourceURLs', 'asins', 'brand', 'categories', 'dateAdded',
       'dateUpdated', 'ean', 'imageURLs', 'keys', 'manufacturer',
       'manufacturerNumber', 'name', 'primaryCategories', 'sourceURLs', 'upc',
       'weight', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29',
       'Unnamed: 30'],
      dtype='object')

In [5]:
pricing_df.columns.str.match('Unnamed')

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True])

In [6]:
pricing_df_2 = pricing_df.loc[:, ~pricing_df.columns.str.contains('Unnamed')]
pricing_df_2.columns

Index(['id', 'prices_amountMax', 'prices_amountMin', 'prices_availability',
       'prices_condition', 'prices_currency', 'prices_dateSeen',
       'prices_isSale', 'prices_merchant', 'prices_shipping',
       'prices_sourceURLs', 'asins', 'brand', 'categories', 'dateAdded',
       'dateUpdated', 'ean', 'imageURLs', 'keys', 'manufacturer',
       'manufacturerNumber', 'name', 'primaryCategories', 'sourceURLs', 'upc',
       'weight'],
      dtype='object')

In [7]:
pricing_df_2['dateAdded'] = pd.to_datetime(pricing_df_2['dateAdded']).dt.tz_convert(None)
pricing_df_2['dateUpdated'] = pd.to_datetime(pricing_df_2['dateUpdated']).dt.tz_convert(None)

C:\Users\Nicole\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\Nicole\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [8]:
pricing_df_2[['prices_dateSeen',
       'dateAdded',
       'dateUpdated']]

,prices_dateSeen,dateAdded,dateUpdated
0,"2017-03-30T06:00:00Z,2017-03-10T22:00:00Z,2017...",2015-04-13 12:00:51,2018-05-12 18:59:48
1,2017-12-14T06:00:00Z,2015-05-18 14:14:56,2018-06-13 19:39:02
2,2017-09-08T05:00:00Z,2015-05-18 14:14:56,2018-06-13 19:39:02
3,2017-10-10T05:00:00Z,2015-05-18 14:14:56,2018-06-13 19:39:02
4,2017-08-28T07:00:00Z,2015-05-18 14:14:56,2018-06-13 19:39:02
...,...,...,...
14587,2015-09-05T00:00:00Z,2015-09-11 02:03:11,2018-06-13 19:43:55
14588,"2017-10-10T19:00:00Z,2017-09-06T17:00:00Z,2017...",2015-09-11 02:03:11,2018-06-13 19:43:55
14589,2018-03-05T11:00:00Z,2015-09-11 02:03:11,2018-06-13 19:43:55
14590,2016-03-22T00:00:00Z,2015-09-11 02:03:11,2018-06-13 19:43:55
14591,2015-12-05T00:00:00Z,2015-09-11 02:03:11,2018-06-13 19:43:55

In [9]:
pricing_df_2.dtypes

id                             object
prices_amountMax              float64
prices_amountMin              float64
prices_availability            object
prices_condition               object
prices_currency                object
prices_dateSeen                object
prices_isSale                    bool
prices_merchant                object
prices_shipping                object
prices_sourceURLs              object
asins                          object
brand                          object
categories                     object
dateAdded              datetime64[ns]
dateUpdated            datetime64[ns]
ean                            object
imageURLs                      object
keys                           object
manufacturer                   object
manufacturerNumber             object
name                           object
primaryCategories              object
sourceURLs                     object
upc                            object
weight                         object
dtype: object

In [10]:
all_dateseen = pricing_df_2['prices_dateSeen'].str.split(',',expand=True)
all_dateseen

,0,1,2,3,4,5,6,7,8,9,...,188,189,190,191,192,193,194,195,196,197
0,2017-03-30T06:00:00Z,2017-03-10T22:00:00Z,2017-03-04T10:00:00Z,2017-03-03T14:00:00Z,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,2017-12-14T06:00:00Z,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,2017-09-08T05:00:00Z,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,2017-10-10T05:00:00Z,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,2017-08-28T07:00:00Z,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14587,2015-09-05T00:00:00Z,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
14588,2017-10-10T19:00:00Z,2017-09-06T17:00:00Z,2017-09-18T15:00:00Z,2017-08-30T05:00:00Z,2017-06-01T18:00:00Z,2017-06-01T10:00:00Z,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
14589,2018-03-05T11:00:00Z,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
14590,2016-03-22T00:00:00Z,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
14591,2015-12-05T00:00:00Z,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [11]:
pricing_df_2.columns

Index(['id', 'prices_amountMax', 'prices_amountMin', 'prices_availability',
       'prices_condition', 'prices_currency', 'prices_dateSeen',
       'prices_isSale', 'prices_merchant', 'prices_shipping',
       'prices_sourceURLs', 'asins', 'brand', 'categories', 'dateAdded',
       'dateUpdated', 'ean', 'imageURLs', 'keys', 'manufacturer',
       'manufacturerNumber', 'name', 'primaryCategories', 'sourceURLs', 'upc',
       'weight'],
      dtype='object')

In [12]:
pricing_df_2['prices_dateSeen'] = pd.to_datetime(all_dateseen[0]).dt.tz_convert(None)

C:\Users\Nicole\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [13]:
pricing_df_2.columns

Index(['id', 'prices_amountMax', 'prices_amountMin', 'prices_availability',
       'prices_condition', 'prices_currency', 'prices_dateSeen',
       'prices_isSale', 'prices_merchant', 'prices_shipping',
       'prices_sourceURLs', 'asins', 'brand', 'categories', 'dateAdded',
       'dateUpdated', 'ean', 'imageURLs', 'keys', 'manufacturer',
       'manufacturerNumber', 'name', 'primaryCategories', 'sourceURLs', 'upc',
       'weight'],
      dtype='object')

In [14]:
pricing_df_2.dtypes

id                             object
prices_amountMax              float64
prices_amountMin              float64
prices_availability            object
prices_condition               object
prices_currency                object
prices_dateSeen        datetime64[ns]
prices_isSale                    bool
prices_merchant                object
prices_shipping                object
prices_sourceURLs              object
asins                          object
brand                          object
categories                     object
dateAdded              datetime64[ns]
dateUpdated            datetime64[ns]
ean                            object
imageURLs                      object
keys                           object
manufacturer                   object
manufacturerNumber             object
name                           object
primaryCategories              object
sourceURLs                     object
upc                            object
weight                         object
dtype: object

In [15]:
unique = pricing_df_2['prices_availability'].unique()
print(unique)

['Yes' 'In Stock' 'TRUE' 'undefined' 'yes' 'Out Of Stock' 'Special Order'
 'No' 'More on the Way' 'sold' 'FALSE' 'Retired' '32 available'
 '7 available' nan 'Limited Stock' 'Discontinued' 'More Coming Soon']

In [16]:
pricing_df_2['prices_availability'] = pricing_df_2['prices_availability'].map({
    ''
'Yes': 'TRUE',
'In Stocke':'TRUE',
'yes': 'TRUE',
'Out Of Stock': 'FALSE',
'Special Order': 'FALSE',
'No': 'FALSE',
'More on the Way': 'FALSE',
'sold':'FALSE',
'Retired':'FALSE',
'32 available': 'TRUE',
'7 available': 'TRUE',
'Limited Stock': 'TRUE',
'Discontinued': 'FALSE',
'More Coming Soon':'FALSE'})

C:\Users\Nicole\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

In [17]:
# pricing_df_2.dropna(subset=['prices_amountMax', 
#                             'prices_amountMin', 
#                             'id',
#                             'prices_availability',
#                             'prices_currency',
#                             'prices_dateSeen',
#                             'prices_isSale',
#                             'dateAdded',
#                             'dateUpdated'])

In [19]:
pricing_df_2.to_csv('../final_project_nt/cleaned4.csv', index = True)