In [1]:
# dependencies
import pandas as pd
from sklearn import *
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from collections import Counter
from sqlalchemy import create_engine
import joblib

In [2]:
# Store environment variable
from getpass import getpass
password = getpass('Enter database password')

Enter database password········

In [3]:
# Connect to RDS Database to query price_data table and store as a pandas DataFrame
url = f"postgresql://postgres:{password}@final-project.crnuve3iih8x.us-east-1.rds.amazonaws.com:5432/postgres"

engine = create_engine(url)

connect = engine.connect()

query = "SELECT * FROM price_data"

df = pd.read_sql(query, con=connect)
df

,index,id,prices_amountMax,prices_amountMin,prices_availability,prices_condition,prices_currency,prices_dateSeen,prices_isSale,prices_merchant,...,ean,imageURLs,keys,manufacturer,manufacturerNumber,name,primaryCategories,sourceURLs,upc,weight
0,0,AVphzgbJLJeJML43fA0o,104.99,104.99,Yes,New,USD,2017-03-30 06:00:00,False,Bestbuy.com,...,None,https://images-na.ssl-images-amazon.com/images...,sanusvlf410b110inchsuperslimfullmotionmountfor...,None,VLF410B1,Sanus VLF410B1 10-Inch Super Slim Full-Motion ...,Electronics,https://www.amazon.com/Sanus-VLF410B1-10-Inch-...,7.93796E+11,32.8 pounds
1,1,AVpgMuGwLJeJML43KY_c,69.00,64.99,In Stock,New,USD,2017-12-14 06:00:00,True,Walmart.com,...,None,https://images-na.ssl-images-amazon.com/images...,boytone2500w21chhometheatersystemblackdiamond/...,Boytone,BT-210F,Boytone - 2500W 2.1-Ch. Home Theater System - ...,Electronics,http://reviews.bestbuy.com/3545/4784804/review...,6.42015E+11,14 pounds
2,2,AVpgMuGwLJeJML43KY_c,69.00,69.00,In Stock,New,USD,2017-09-08 05:00:00,False,Walmart.com,...,None,https://images-na.ssl-images-amazon.com/images...,boytone2500w21chhometheatersystemblackdiamond/...,Boytone,BT-210F,Boytone - 2500W 2.1-Ch. Home Theater System - ...,Electronics,http://reviews.bestbuy.com/3545/4784804/review...,6.42015E+11,14 pounds
3,3,AVpgMuGwLJeJML43KY_c,69.99,69.99,Yes,New,USD,2017-10-10 05:00:00,False,Bestbuy.com,...,None,https://images-na.ssl-images-amazon.com/images...,boytone2500w21chhometheatersystemblackdiamond/...,Boytone,BT-210F,Boytone - 2500W 2.1-Ch. Home Theater System - ...,Electronics,http://reviews.bestbuy.com/3545/4784804/review...,6.42015E+11,14 pounds
4,4,AVpgMuGwLJeJML43KY_c,66.99,66.99,Yes,New,USD,2017-08-28 07:00:00,False,Bestbuy.com,...,None,https://images-na.ssl-images-amazon.com/images...,boytone2500w21chhometheatersystemblackdiamond/...,Boytone,BT-210F,Boytone - 2500W 2.1-Ch. Home Theater System - ...,Electronics,http://reviews.bestbuy.com/3545/4784804/review...,6.42015E+11,14 pounds
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14491,14587,AVpgibRDLJeJML43PTZX,65.99,65.99,None,New,USD,2015-09-05 00:00:00,True,Other,...,None,http://pisces.bbystatic.com/image2/BestBuy_US/...,naxa42soundbarwithbluetooth_builtinsubwoofer/0...,Naxa,SPNA7008,naxa - 2.1-Channel Soundbar with 50-Watt Digit...,Electronics,https://www.walmart.com/reviews/product/441840...,8.40005E+11,4.1 pounds
14492,14588,AVpgibRDLJeJML43PTZX,58.99,58.99,Yes,New,USD,2017-10-10 19:00:00,False,Bestbuy.com,...,None,http://pisces.bbystatic.com/image2/BestBuy_US/...,naxa42soundbarwithbluetooth_builtinsubwoofer/0...,Naxa,SPNA7008,naxa - 2.1-Channel Soundbar with 50-Watt Digit...,Electronics,https://www.walmart.com/reviews/product/441840...,8.40005E+11,4.1 pounds
14493,14589,AVpgibRDLJeJML43PTZX,58.49,58.49,In Stock,New,USD,2018-03-05 11:00:00,False,Walmart.com,...,None,http://pisces.bbystatic.com/image2/BestBuy_US/...,naxa42soundbarwithbluetooth_builtinsubwoofer/0...,Naxa,SPNA7008,naxa - 2.1-Channel Soundbar with 50-Watt Digit...,Electronics,https://www.walmart.com/reviews/product/441840...,8.40005E+11,4.1 pounds
14494,14590,AVpgibRDLJeJML43PTZX,77.98,77.98,None,New,USD,2016-03-22 00:00:00,True,Other,...,None,http://pisces.bbystatic.com/image2/BestBuy_US/...,naxa42soundbarwithbluetooth_builtinsubwoofer/0...,Naxa,SPNA7008,naxa - 2.1-Channel Soundbar with 50-Watt Digit...,Electronics,https://www.walmart.com/reviews/product/441840...,8.40005E+11,4.1 pounds
14495,14591,AVpgibRDLJeJML43PTZX,71.95,71.95,None,New,USD,2015-12-05 00:00:00,False,Walmart.com,...,None,http://pisces.bbystatic.com/image2/BestBuy_US/...,naxa42soundbarwithbluetooth_builtinsubwoofer/0...,Naxa,SPNA7008,naxa - 2.1-Channel Soundbar with 50-Watt Digit...,Electronics,https://www.walmart.com/reviews/product/441840...,8.40005E+11,4.1 pounds

In [4]:
# Create features dataframe
price_df = pd.DataFrame({'id': df['id'],
                         'Quarter': pd.DatetimeIndex(pd.to_datetime(df['prices_dateSeen'])).quarter,
                         'Month': pd.DatetimeIndex(pd.to_datetime(df['prices_dateSeen'])).month,
                         'prices_amountMin': df['prices_amountMin'],
                         'prices_condition': df['prices_condition'],
                         'prices_merchant': df['prices_merchant'],
                         'isSale': df['prices_isSale']
                        })
price_df.dropna(inplace=True)

In [5]:
# Determine the number of unique values in each column
price_df.nunique()

id                  1245
Quarter                4
Month                 12
prices_amountMin    4853
prices_condition       2
prices_merchant        5
isSale                 2
dtype: int64

In [6]:
# value counts on merchant data
price_df['prices_merchant'].value_counts()

Other               5410
Bestbuy.com         4551
bhphotovideo.com    2744
Walmart.com         1395
Amazon.com           396
Name: prices_merchant, dtype: int64

In [7]:
# Create X dataframe
X_df = price_df.drop('isSale', axis=1)
X_df = X_df
X_df

,id,Quarter,Month,prices_amountMin,prices_condition,prices_merchant
0,AVphzgbJLJeJML43fA0o,1,3,104.99,New,Bestbuy.com
1,AVpgMuGwLJeJML43KY_c,4,12,64.99,New,Walmart.com
2,AVpgMuGwLJeJML43KY_c,3,9,69.00,New,Walmart.com
3,AVpgMuGwLJeJML43KY_c,4,10,69.99,New,Bestbuy.com
4,AVpgMuGwLJeJML43KY_c,3,8,66.99,New,Bestbuy.com
...,...,...,...,...,...,...
14491,AVpgibRDLJeJML43PTZX,3,9,65.99,New,Other
14492,AVpgibRDLJeJML43PTZX,4,10,58.99,New,Bestbuy.com
14493,AVpgibRDLJeJML43PTZX,1,3,58.49,New,Walmart.com
14494,AVpgibRDLJeJML43PTZX,1,3,77.98,New,Other
14495,AVpgibRDLJeJML43PTZX,4,12,71.95,New,Walmart.com

# Data Preprocessing

In [8]:
# Encode id and merchant data & save encoders for future use
id_encoder = LabelEncoder()
cond_encoder = LabelEncoder()
merch_encoder = LabelEncoder()

X = X_df.copy()

id_encoder.fit(X['id'])
cond_encoder.fit(X['prices_condition'])
merch_encoder.fit(X['prices_merchant'])

X['id'] = id_encoder.transform(X['id'])
X['prices_condition'] = cond_encoder.transform(X['prices_condition'])
X['prices_merchant'] = merch_encoder.transform(X['prices_merchant'])

# Save encoders
joblib.dump(id_encoder, 'ID_Encoder.sav')
joblib.dump(cond_encoder, 'Condition_Encoder.sav')
joblib.dump(merch_encoder, 'Merchant_Encoder.sav')
X

,id,Quarter,Month,prices_amountMin,prices_condition,prices_merchant
0,831,1,3,104.99,0,1
1,652,4,12,64.99,0,3
2,652,3,9,69.00,0,3
3,652,4,10,69.99,0,1
4,652,3,8,66.99,0,1
...,...,...,...,...,...,...
14491,703,3,9,65.99,0,2
14492,703,4,10,58.99,0,1
14493,703,1,3,58.49,0,3
14494,703,1,3,77.98,0,2
14495,703,4,12,71.95,0,3

In [9]:
# Create y dataframe
y = price_df['isSale']
y.value_counts()

False    11012
True      3484
Name: isSale, dtype: int64

In [10]:
# Splitting into Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
Counter(y_train)

Counter({False: 8277, True: 2595})

In [11]:
# Use RandomOverSampler to obtain more "True" samples to train our model.
# Reason: 'isSale' appears to be "FALSE" more often than "TRUE"
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({False: 8277, True: 8277})

In [12]:
# Creating StandardScaler instance
scaler = StandardScaler()

# Fitting Standard Scaler
X_scaler = scaler.fit(X_resampled)

# Scaling data
X_train_scaled = X_scaler.transform(X_resampled)
X_test_scaled = X_scaler.transform(X_test)

# Save scaler
joblib.dump(X_scaler, 'Data_Scaler.sav')

['Data_Scaler.sav']

In [13]:
# check shape of training/testing data sets
print(X_train_scaled.shape)
print(X_test.shape)
print(y_resampled.shape)
print(y_test.shape)

(16554, 6)
(3624, 6)
(16554,)
(3624,)

# Testing Machine Learning Models

In [14]:
ml_models = {
    "Decision Tree Classifier": tree.DecisionTreeClassifier(),
    "Random Forest Classifiers": ensemble.RandomForestClassifier(),
    "Logistic Regression": linear_model.LogisticRegression(),
    "Support Vector Machines": svm.SVC(),
    "Bernoulli Naive Bayes": naive_bayes.BernoulliNB(),
    "Gaussian Naive Bayes": naive_bayes.GaussianNB(),
}
results = []
for m in ml_models:
    print(m)
    model = ml_models[m]
    model.fit(X_train_scaled, y_resampled)
    predictions = model.predict(X_test_scaled)
    accuracy = model.score(X_test_scaled, y_test)
    report = classification_report(y_test, predictions, output_dict=True)
    results.append({
        "Name": m,
        "Accuracy": accuracy,
        "Model": ml_models[m],
        "'False' Precision": report['False']['precision'],
        "'False' Recall": report['False']['recall'],
        "'True' Precision": report['True']['precision'],
        "'True' Recall": report['True']['recall']
    })
    print('Done')
pd.DataFrame(results)

Decision Tree Classifier
Done
Random Forest Classifiers
Done
Logistic Regression
Done
Support Vector Machines
Done
Bernoulli Naive Bayes
Done
Gaussian Naive Bayes
Done

,Name,Accuracy,Model,'False' Precision,'False' Recall,'True' Precision,'True' Recall
0,Decision Tree Classifier,0.705298,DecisionTreeClassifier(),0.804531,0.805119,0.399098,0.398200
1,Random Forest Classifiers,0.714956,"(DecisionTreeClassifier(max_features='auto', r...",0.805237,0.820841,0.413876,0.389201
2,Logistic Regression,0.518764,LogisticRegression(),0.795821,0.487386,0.280657,0.615298
3,Support Vector Machines,0.597958,SVC(),0.848419,0.568921,0.341341,0.687289
4,Bernoulli Naive Bayes,0.532837,BernoulliNB(),0.815375,0.492505,0.296146,0.656918
5,Gaussian Naive Bayes,0.301049,GaussianNB(),0.879699,0.085558,0.255211,0.964004

In [15]:
# Choose machine learning model with highest accuracy
ml_model = pd.DataFrame(results).sort_values("Accuracy", ascending=False).iloc[0].Model
ml_model

RandomForestClassifier()

In [16]:
# Fit selected model to the data
ml_model = ml_model.fit(X_train_scaled, y_resampled)

In [17]:
# Making predictions using the testing data
predictions = ml_model.predict(X_test_scaled)
predictions

array([ True, False, False, ..., False, False, False])

In [18]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)

# Calculating the accuracy score
acc_score = accuracy_score(y_test, predictions)

In [19]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0         2243          492
Actual 1          551          338

Accuracy Score : 0.71219646799117
Classification Report
              precision    recall  f1-score   support

       False       0.80      0.82      0.81      2735
        True       0.41      0.38      0.39       889

    accuracy                           0.71      3624
   macro avg       0.61      0.60      0.60      3624
weighted avg       0.71      0.71      0.71      3624

In [20]:
# Save ML model
joblib.dump(ml_model, 'ML_Model.sav')

['ML_Model.sav']

In [21]:
# read in user input from website -- TEST/HYPOTHETICAL INPUT FOR NOW
user_input = pd.DataFrame({'id': 'AVpgMuGwLJeJML43KY_c',
                           'Quarter': 2,
                           'Month': 6,
                           'prices_amountMin': 64,
                           'prices_condition': 'Used',
                           'prices_merchant': 'Walmart.com'
                          }, index=[0])

In [22]:
# Load encoders with:
# id_encoder = joblib.load('ID_Encoder.sav')
# cond_encoder = joblib.load('Condition_Encoder.sav')
# merch_encoder = joblib.load('Merchant_Encoder.sav')

# encode user input with id_encoder and merch_encoder
user_input_encoded = user_input.copy()
user_input_encoded['id'] = id_encoder.transform(user_input['id'])
user_input_encoded['prices_condition'] = cond_encoder.transform(user_input['prices_condition'])
user_input_encoded['prices_merchant'] = merch_encoder.transform(user_input['prices_merchant'])
user_input_encoded

    id  Quarter  Month  prices_amountMin  prices_condition  prices_merchant
0  652        2      6                64                 1                3

In [23]:
# Load data scaler using:
# X_scaler = joblib.load('Data_Scaler.sav')

# Use X_scaler to transform encoded user input
user_input_encoded_scaled = X_scaler.transform(user_input_encoded)

In [24]:
# Load ML model using:
# ml_model = joblib.load('ML_Model.sav')

# Evaluate user input sales price (True indicates price is discounted / False indicates price is not discounted)
ml_model.predict(user_input_encoded_scaled)[0]

False